### ISSUE TITLE
Controller Handler Function no longer found after upgrading v3.8.0 to v3.9.0

### ISSUE THREAD

**Issue by chuckberrry** [ui5-community/ui5-ecosystem-showcase#1258]
**Describe the bug**
After upgrading from version 3.8.0 to 3.9.0, my handler functions can no longer be found in my SAPUI5 application.

The following warning message is displayed in the browser console:

[FUTURE FATAL] Element sap.ui.core.mvc.XMLView#container---Mainview: event handler function "onPress" is not a function or does not exist in the controller. -  

Consequently, no handler function is called when actions are triggered (e.g., when a button is pressed).

The debug logs from ui5-tooling-transpile-middleware look fine. All TS files are transpiled and available in the browser sources.

The problem only occurs when I upgrade from version 3.8.0 to 3.9.0.

**Expected behavior**
Controller handler function should be registered correctly.

**Versions:**
  "dependencies": {
    "@sap/approuter": "^20.6.0",
    "config": "^4.1.1",
    "jwt-decode": "^4.0.0"
  },
  "devDependencies": {
    "@sap/ux-ui5-tooling": "^1.18.6",
    "@sapui5/types": "^1.139.0",
    "@types/dompurify": "^3.2.0",
    "@typescript-eslint/eslint-plugin": "^7.18.0",
    "@typescript-eslint/parser": "^7.18.0",
    "@ui5/cli": "^4.0.23",
    "babel-plugin-istanbul": "^7.0.0",
    "eslint": "^8.57.1",
    "nyc": "^17.1.0",
    "puppeteer": "^24.17.0",
    "sinon": "^21.0.0",
    "start-server-and-test": "^2.0.13",
    "ts-node": "^10.9.2",
    "typescript": "^5.9.2",
    "ui5-middleware-approuter": "^3.6.2",
    "ui5-middleware-livereload": "^3.1.2",
    "ui5-middleware-simpleproxy": "^3.4.3",
    "ui5-test-runner": "^5.9.1",
    "ui5-tooling-transpile": "^3.9.0"
  }
